### ISSUE TITLE
Sles for SAP not recognizing some distro commands

### ISSUE THREAD

**Issue by lenneker** [python-distro/distro#273] opened 2021-05-18 14:53 UTC
I tried install the new pip version

```
zypper install python3-pip

pip3.6 install --upgrade pip

```
then i receive the folowwin error

```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 241, in run
    with self._build_session(options) as session:
  File "/usr/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 81, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/usr/lib/python3.6/site-packages/pip/_internal/download.py", line 339, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/lib/python3.6/site-packages/pip/_internal/download.py", line 102, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution()),
  File "/usr/lib/python3.6/site-packages/pip/_vendor/distro.py", line 120, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/distro.py", line 634, in linux_distribution
    self.version(),
  File "/usr/lib/python3.6/site-packages/pip/_vendor/distro.py", line 688, in version
    self.lsb_release_attr('release'),
  File "/usr/lib/python3.6/site-packages/pip/_vendor/distro.py", line 836, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/usr/lib/python3.6/site-packages/pip/_vendor/distro.py", line 522, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/distro.py", line 933, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/site-packages/run/__init__.py", line 145, in __new__
    process = cls.create_process(command, stdin, cwd=cwd, env=env, shell=shell)
  File "/usr/lib/python3.6/site-packages/run/__init__.py", line 121, in create_process
    shlex.split(command),
  File "/usr/lib64/python3.6/shlex.py", line 305, in split
    return list(lex)
  File "/usr/lib64/python3.6/shlex.py", line 295, in __next__
    token = self.get_token()
  File "/usr/lib64/python3.6/shlex.py", line 105, in get_token
    raw = self.read_token()
  File "/usr/lib64/python3.6/shlex.py", line 136, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'tuple' object has no attribute 'read'
Traceback (most recent call last):
  File "/usr/bin/pip3.6", line 11, in <module>
    load_entry_point('pip==10.0.1', 'console_scripts', 'pip3.6')()
  File "/usr/lib/python3.6/site-packages/pip/_internal/__init__.py", line 246, in main
    return command.main(cmd_args)
  File "/usr/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 264, in main
    timeout=min(5, options.timeout)) as session:
  File "/usr/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 81, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/usr/lib/python3.6/site-packages/pip/_internal/download.py", line 339, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/lib/python3.6/site-packages/pip/_internal/download.py", line 102, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution()),
  File "/usr/lib/python3.6/site-packages/pip/_vendor/distro.py", line 120, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/distro.py", line 634, in linux_distribution
    self.version(),
  File "/usr/lib/python3.6/site-packages/pip/_vendor/distro.py", line 688, in version
    self.lsb_release_attr('release'),
  File "/usr/lib/python3.6/site-packages/pip/_vendor/distro.py", line 836, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/usr/lib/python3.6/site-packages/pip/_vendor/distro.py", line 522, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/distro.py", line 933, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/site-packages/run/__init__.py", line 145, in __new__
    process = cls.create_process(command, stdin, cwd=cwd, env=env, shell=shell)
  File "/usr/lib/python3.6/site-packages/run/__init__.py", line 121, in create_process
    shlex.split(command),
  File "/usr/lib64/python3.6/shlex.py", line 305, in split
    return list(lex)
  File "/usr/lib64/python3.6/shlex.py", line 295, in __next__
    token = self.get_token()
  File "/usr/lib64/python3.6/shlex.py", line 105, in get_token
    raw = self.read_token()
  File "/usr/lib64/python3.6/shlex.py", line 136, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'tuple' object has no attribute 'read'

```
so i went to python

![image](https://user-images.githubusercontent.com/56844930/118673054-15653680-b7cf-11eb-8ac8-edc04e5f4309.png)

![image](https://user-images.githubusercontent.com/56844930/118672709-d46d2200-b7ce-11eb-9648-281fd0f6673e.png)

the distro commands returns the id but is not returning the version.

so i think than this is  the problem

![image](https://user-images.githubusercontent.com/56844930/118673303-45acd500-b7cf-11eb-88e4-bc62dfec6784.png)

i cant execute any command with pip who do install and uninstall.

anny idea how to resolve this problem and have a working pip?

i tried manual install but not work with

```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py
python3 get-pip.py
```

**Comment by HorlogeSkynet** [comment] 2021-05-24 15:22
Could you please give the output for `lsb_release -a` on your system ? Thanks 🙇

**Comment by lenneker** [comment] 2021-05-28 12:38
![image](https://user-images.githubusercontent.com/56844930/119984907-5d871480-bf98-11eb-93a2-3e9b1a3e103b.png)

**Comment by HorlogeSkynet** [comment] 2021-09-25 15:43
So it appears this issue is a duplicate of #222 (see upstream xando/subprocess.run#5 for rationale).
Could you verify that you actually got a `subprocess.run` Python package installed on your system ?

Also see pypa/pip#5467 & Azure/WALinuxAgent#1705.

Bye 👋

**Closed** 2021-09-25 18:12 UTC
Labels: resolution: duplicate, bug
